//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elj.appdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shedule
    {
        public int idSchedule { get; set; }
        public int idGroup { get; set; }
        public int idTimeTable { get; set; }
        public short dayOfWeek { get; set; }
        public int idTeachSub { get; set; }
    
        public virtual StudGroup StudGroup { get; set; }
        public virtual TeachSubject TeachSubject { get; set; }
        public virtual TimeTable TimeTable { get; set; }
        public virtual WeekDay WeekDay { get; set; }
    }
}
