//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elj.appdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPerfomance
    {
        public int idStudPerf { get; set; }
        public int idStud { get; set; }
        public short mark { get; set; }
        public bool attendMark { get; set; }
        public int idSchedule { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
